version: 0.2

phases:
  install:
    commands:
      - echo "No dependencies to install for static website"
  build:
    commands:
      - echo "No build step required. Preparing artifacts..."

artifacts:
  files:
    - '**/*'
  base-directory: .
  discard-paths: no
